// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: VehicleCANData.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Aro.Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GPSPosition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public double Lat { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public double Lng { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleCANData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ComponentType From { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ComponentType To { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Sequence { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public MessageAckType AckType { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int VehicleSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public GearModeEnum GearMode { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public DrivingReadyEnum DrivingReady { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int DrivingHour { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int DrivingMinutes { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public int DrivingDistance { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public int BatteryRemains { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public OnOffEnum BatteryCharing { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public int AvailableDistance { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public OnOffEnum TailLamp { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public OnOffEnum FogLamp { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public OnOffEnum HeadLampHigh { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public OnOffEnum HeadLampLow { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public DirectionSignalEnum TurnSignalLamp { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public OnOffEnum EmergencyLamp { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public OnOffEnum EmergencySwitchMode { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public OnOffEnum CabinCombineStatus { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public DrivingModeEnum DrivingMode { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public int OutTemperature { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public int CabinClimate { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public CabinDoorStatus CabinDoorStatus { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public OnOffEnum StopBellStatus { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public int GpsTimeHour { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public int GpsTimeMinutes { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public GpsStatusEnum GpsStatus { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public GPSPosition GpsInfo { get; set; }

        [global::ProtoBuf.ProtoMember(32)]
        public int CurrentStation { get; set; }

        [global::ProtoBuf.ProtoMember(33)]
        public int DestinationStation { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public int StationDistance { get; set; }

        [global::ProtoBuf.ProtoMember(35)]
        public int IntersectionDistance { get; set; }

        [global::ProtoBuf.ProtoMember(36)]
        public int BumpDistance { get; set; }

        [global::ProtoBuf.ProtoMember(37)]
        public int Heading { get; set; }

        [global::ProtoBuf.ProtoMember(38)]
        public int INSStatus { get; set; }

        [global::ProtoBuf.ProtoMember(39)]
        public int AVSensor { get; set; }

        [global::ProtoBuf.ProtoMember(40)]
        public int AVsw { get; set; }

        [global::ProtoBuf.ProtoMember(41)]
        public int AVError { get; set; }

        [global::ProtoBuf.ProtoMember(42)]
        public bool Moving { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum GearModeEnum
    {
        ModeP = 0,
        ModeR = 1,
        ModeN = 2,
        ModeD = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OnOffEnum
    {
        ModeOff = 0,
        ModeOn = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DrivingReadyEnum
    {
        DrivingNotReady = 0,
        DrivingReady = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DirectionSignalEnum
    {
        DirectionNormal = 0,
        DirectionLeft = 1,
        DirectionRight = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DrivingModeEnum
    {
        DrivingManual = 0,
        DrivingAutonomous = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CabinDoorStatus
    {
        DoorClosed = 0,
        DoorOpening = 1,
        DoorClosing = 2,
        DoorOpened = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum GpsStatusEnum
    {
        GpsNormal = 0,
        GpsAbnormal = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ComponentType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"Component_UI")]
        ComponentUI = 0,
        ComponentAroMgr = 1,
        ComponentCameraMgr = 2,
        ComponentVehicleMgr = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MessageAckType
    {
        NoAck = 0,
        NeedAck = 1,
        NeedResponse = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
